### PR TITLE
Added some apk stuff

### PR DESCRIPTION
**Pull request by Technologx**
Added this: applicationVariants.all { variant -> variant.outputs.each { output -> output.outputFile = new File(output.outputFile.parent, "${applicationId}-v${variant.versionName}.apk") } }
for users to enjoy

### CODE REVIEW

**Comment by Technologx** [comment]
You should be able to change it easily I deleted this project from my laptop because I wasn't getting any help.

**Comment by Technologx** [comment]
Try what I did now hopefully it'll work like it should.

**Comment by Technologx** [comment]
Yea but having it the way I have it makes things easier plus users should know which flavor they built because AS asks which one they want to build.

**Comment by 1hakr** [comment]
If some one wants to build multiple variants at the same time, they wont be as they will replace as they have the same name. Closing this PR for now.

**Comment by Technologx** [comment]
Could you un-close this that way I can help you get this solved?

**Comment by 1hakr** [comment]
sure mate.

**Comment by Technologx** [comment]
Thank you also I need help with my issues I'm having I really like the look of your app and would love to use it?

**Comment by 1hakr** [comment]
Sure @Technologx . Add your issues in github and i will see what i can do

**Comment by Technologx** [comment]
Alright I'll submit my issues once I get this wallpaper dashboard I'm working on finished

**Comment by 1hakr** [comment]
Hey i think the code can be simplified further 
`
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def newApkName = "${parent.name}-${output.baseName}-${variant.versionName}.apk"
            output.outputFile = new File(output.outputFile.parent, newApkName)
        }
    }
`

**Comment by Technologx** [comment]
That could work I think we could keep the date part and comment it out give users the option to have it if they want it.

**Comment by Technologx** [comment]
Not sure how to really do it since we're dealing with flavors instead of 1 variant.

**Comment by 1hakr** [comment]
so gradle automatically builds the baseName which is based on product flavours, we can just reuse it. Can you make a new PR, with the suggested changes i have given. I have tested it and it works. I'm closing this PR

**Pull request closed without merging**
