### PR TITLE
Call to getAppname returns bad names.

### PR DESCRIPTION
**Pull request by dionysiosarvanitis**

### CODE REVIEW

**Comment by 1hakr** [comment]
This is actually an improvement . please refer commit 22a766c38f3b1cec4dd0b7ede4785776eb9f102b

**Comment by dionysiosarvanitis** [comment]
Any special reason you prefer the bad names instead of good ones? :)

**Comment by 1hakr** [comment]
I actually prefer the full proper names, but the thing is it loadLabel() takes significant amount of time and it slows down loading of apps. Its clearly visible.

**Comment by dionysiosarvanitis** [comment]
Loading of apps is instant to me, but loading of processes takes a second. That's because of `getProcessSize()`.

Maybe it's better to have full proper names in processes only and keep the app names clean. Anyway names does not appear to be set correctly. If you just want to remove the android from the end you should do something like this inside the try block

```java
int start = packageName.lastIndexOf('.');
tmp = start != -1 ? packageName.substring(start+1) : "";
if(tmp.equalsIgnoreCase("android")){
    name = packageName.substring(0, start);
}

![screenshot jan 28](https://cloud.githubusercontent.com/assets/1359269/5946399/0c86e05c-a73e-11e4-88a0-b23792bdd859.png)

**Pull request closed without merging**
